export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
export const UPDATE_CURRENT_INDEX = "UPDATE_CURRENT_INDEX";

export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_ITEM_COUNT = "INCREASE_ITEM_COUNT";
export const DECREASE_ITEM_COUNT = "DECREASE_ITEM_COUNT";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const CHECK_PROMOCODE_START = "CHECK_PROMOCODE_START";
export const CHECK_PROMOCODE_SUCCESS = "CHECK_PROMOCODE_SUCCESS";
export const CHECK_PROMOCODE_ERROR = "CHECK_PROMOCODE_ERROR";
export const PROCEED_TO_SHIPPING = "PROCEED_TO_SHIPPING";
export const PROCEED_TO_CONFIRM = "PROCEED_TO_CONFIRM";
